relo:
    priorDir: "/home/ian/catkin_ws/data_loc"
    cloudTopic: "/cloud_registered"
    poseTopic: "/Odometry"
    searchDis: 5.0
    searchNum: 3  # if the cloud is dense, please reset it to 1
    trustDis: 5.0
    # 0: ICP 1: AA-ICP 2: Our Fast ICP 3: Our Robust ICP 4: Our Fast and Robust ICP 5: ICP Point-to-plane
    # 6: Our Fast and Robust ICP point to plane 7: Sparse ICP 8: Sparse ICP point to plane
    regMode: 4 # (0~8), but methods 5, 6 and 8 need normal information

    # extrinsic_T: [ -0.026102, 0.038266, -0.297789]  # 本次使用
    # extrinsic_R: [ 0.999610, 0.027142, 0.006595,
    #               0.027188, -0.999606, -0.006972,
    #              0.006403, 0.007149, -0.999954]
    extrinsic_T: [ 0.031, -0.10, 0.11]  # seu velo16
    extrinsic_R: [ 0.9994142, 0.03275957, 0.00990251,
                  -0.03266505,  0.99942062, -0.00956125,
                  -0.01021,  0.00923218,  0.99990526]
